// Generated by COREKEYS-generator

#ifndef COREKEYS_H
#define COREKEYS_H

#include <string>

class CoreKeys {

public:
    static std::string get(uint32_t master_byte, std::string master_id, uint32_t key_byte, std::string key_id);
private:
    static std::string get_master_key(uint32_t master_seed, std::string id);
    static std::string get_encrypted_key(uint32_t key_seed, std::string key_id);

private:
    class Disarray {
    public:
        static int get_seed(uint32_t magic_val);
        static uint8_t SEED_INDEX;
        static uint32_t ADJUSTMENT_VALUE;
        static char* seeds;
        static char* disarray1;
        static char* disarray2;
        static char* disarray3;
        static char* disarray4;
    };

};


#endif
